[[project]]
title = "Consultant – Reos Partners"
category = "Consultancy"
image = "./config/assets/projects/project-1.jpg"
url = "https://reospartners.com"

[[project]]
title = "Consultant – Asia Group Advisors"
category = "Consultancy"
image = "./config/assets/projects/project-2.png"
url = "https://agasean.com"

[[project]]
title = "Consultant – Tropical Marine Science Institute"
category = "Consultancy"
image = "./config/assets/projects/project-3.jpg"
url = "https://www.tmsi.nus.edu.sg"

[[project]]
title = "Consultant – Centre for International Law (NUS)"
category = "Consultancy"
image = "./config/assets/projects/project-4.png"
url = "https://cil.nus.edu.sg"

[[project]]
title = "Consultant – European Joint Master in Water & Coastal Management"
category = "Teaching"
image = "./config/assets/projects/project-5.png"
url = "https://eacea.ec.europa.eu/erasmus-plus/library/european-education-area_en"
