[[post]]
category = "Publications"
title = "Climate risk & hydrology research"
subtitle = "Full list of journal articles and conference papers available online."
datetime = "2024-01-01"
image = "./config/assets/posts/blog-1.jpg"
url = "https://www.tinyurl.com/reds-publication"
