# https://ionic.io/ionicons
# <ion-icon name="[[name]]"></ion-icon>
# name = "https://example.com/"

logo-linkedin = "https://www.linkedin.com/in/dadiyortowendi"
logo-github = "https://github.com/dadiyorto"
logo-twitter = "https://twitter.com/dadiyorto"
logo-instagram = "https://www.instagram.com/dadiyorto.wendi"
logo-facebook = "https://www.facebook.com/dadiyorto.wendi"
