############### Section config ##################
#################################################
title = "Key Strengths"
enabled = true # false

################ Skills #########################
#################################################
[[skills]]
title = "Climate & Flood Risk Modelling"
icon = "./config/assets/icons/gear.svg"
text = "Design climate and flood risk models linking historical data, scenarios, and actionable insights."

[[skills]]
title = "Geospatial Data Science"
icon = "./config/assets/icons/compass.svg"
text = "Deliver geospatial analyses, mapping, and risk overlays for data-driven decisions."

[[skills]]
title = "Hydrology & Water Resources"
icon = "./config/assets/icons/mobile.svg"
text = "Lead hydrological studies on water resources, flood hydrology, and coastal impacts."

[[skills]]
title = "Project & Product Leadership"
icon = "./config/assets/icons/team.svg"
text = "Manage interdisciplinary teams and coordinate stakeholders to deliver climate resilience products."
