############### Section config ##################
#################################################
title = "IT Competencies"
enabled = true

############### Technologies ####################
#################################################
[technologies]
python = "./config/assets/icons/python.svg"
pandas = "./config/assets/icons/pandas.svg"
jupyter = "./config/assets/icons/jupyter.svg"
ai = "./config/assets/icons/ai.svg"
git = "./config/assets/icons/git.svg"
mongodb = "./config/assets/icons/mongodb.svg"
html = "./config/assets/icons/html.svg"
linux = "./config/assets/icons/linux.svg"
